"""
Alert Manager

Handles driver safety alerts generated by the Central Safety Engine.

The Alert Manager does NOT perform detection or safety reasoning.
It only controls:
    - event-based alert triggering
    - cooldown/debouncing
    - temporary visual alert display
    - alert history
"""

import time


class AlertManager:
    """
    Manages driver safety alerts.

    Important V2 behavior:
        An alert is triggered when an alert condition ENTERS the active
        state, not on every frame while the condition remains active.

        Example:
            DROWSINESS starts -> one alert
            DROWSINESS continues -> no repeated alert
            DROWSINESS ends -> state is cleared
            DROWSINESS happens again -> one new alert
    """

    def __init__(self, cooldowns=None, display_duration=2.5):
        self.cooldowns = cooldowns or {
            "DROWSINESS_ALERT": 3.0,
            "PHONE_ALERT": 3.0,
            "SEATBELT_ALERT": 5.0,
            "YAWNING_ALERT": 5.0,
            "DROWSINESS_WARNING": 3.0,
        }

        self.display_duration = float(display_duration)

        # Alert types that were active on the previous frame.
        self.active_alert_types = set()

        # Last time an alert type was actually delivered.
        self.last_alert_time = {}

        # Until when each delivered alert should remain visible in the UI.
        self.display_until = {}

        # Delivered alert history.
        self.alert_history = []

    def _can_trigger(self, alert_type, timestamp):
        last_time = self.last_alert_time.get(alert_type)

        if last_time is None:
            return True

        cooldown = self.cooldowns.get(alert_type, 3.0)
        return (timestamp - last_time) >= cooldown

    def _deliver_alert(self, alert, timestamp):
        alert_type = alert.get("type", "UNKNOWN_ALERT")
        severity = alert.get("severity", "UNKNOWN")
        message = alert.get(
            "message",
            "Safety alert detected."
        )

        print()
        print("!" * 70)
        print(f"DRIVER SAFETY ALERT [{severity}]")
        print(f"Type    : {alert_type}")
        print(f"Message : {message}")
        print("!" * 70)

        self.last_alert_time[alert_type] = timestamp
        self.display_until[alert_type] = (
            timestamp + self.display_duration
        )

        self.alert_history.append({
            "timestamp": timestamp,
            "type": alert_type,
            "severity": severity,
            "message": message,
        })

    def process(self, safety_result, timestamp=None):
        """
        Process alerts from CentralSafetyEngine.

        Alerts are edge-triggered:
            inactive -> active = trigger
            active -> active   = suppress
            active -> inactive = reset
        """

        if timestamp is None:
            timestamp = time.monotonic()

        alerts = safety_result.get("alerts", [])

        current_alert_types = {
            alert.get("type", "UNKNOWN_ALERT")
            for alert in alerts
        }

        # Only alert types that appeared now but were not active
        # on the previous frame are considered new events.
        newly_active_types = (
            current_alert_types
            - self.active_alert_types
        )

        triggered_alerts = []
        suppressed_alerts = []

        for alert in alerts:
            alert_type = alert.get(
                "type",
                "UNKNOWN_ALERT"
            )

            if alert_type not in newly_active_types:
                suppressed_alerts.append(alert)
                continue

            if self._can_trigger(
                alert_type,
                timestamp
            ):
                self._deliver_alert(
                    alert,
                    timestamp
                )
                triggered_alerts.append(alert)
            else:
                suppressed_alerts.append(alert)

        # Save current active condition set for edge detection
        # on the next frame.
        self.active_alert_types = current_alert_types

        # Remove expired visual alerts.
        expired = [
            alert_type
            for alert_type, end_time
            in self.display_until.items()
            if timestamp >= end_time
        ]

        for alert_type in expired:
            del self.display_until[alert_type]

        display_alerts = []

        for alert in self.alert_history:
            if (
                alert["type"] in self.display_until
                and timestamp
                < self.display_until[alert["type"]]
            ):
                display_alerts.append(alert)

        # Show only the most recent alert per type, and order
        # them by delivery time.
        display_alerts.sort(
            key=lambda item: item["timestamp"]
        )

        return {
            # This flag is for the temporary UI notification.
            "alert_active": len(display_alerts) > 0,

            "triggered_count": len(triggered_alerts),

            "suppressed_count": len(suppressed_alerts),

            "triggered_alerts": triggered_alerts,

            "suppressed_alerts": suppressed_alerts,

            "display_alerts": display_alerts,

            "total_history": len(self.alert_history),
        }

    def get_history(self):
        return list(self.alert_history)

    def clear_history(self):
        self.alert_history.clear()

    def reset(self):
        self.active_alert_types.clear()
        self.last_alert_time.clear()
        self.display_until.clear()
        self.alert_history.clear()
